### PR TITLE
YJP-000: Test

### PR DESCRIPTION
**Pull request by jowo-io**
Testing 🏗

### CODE REVIEW

**Comment by jowo-io** [comment]
Your pull request is now being monitored; comment "Please help" for more info. View the [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please merge

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please merge

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
proccess is not defined

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚠️ Please check status checks for more details.

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚠️ Please check status checks for more details.

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚠️ Please check status checks for more details.

**Comment by jowo-io** [comment]
please count reviews

**Comment by jowo-io** [comment]
please helm

**Comment by jowo-io** [comment]
please help

**Comment by jowo-io** [comment]
JunoBot is here to help. Currently I support only 3 commands:

    Please merge

This will trigger a merge request. In order to complete the merge, I will check
that the PR is mergeable (no conflicts), and that it has passed all of the status
checks. The merge strategy ('merge' or 'squash') is based on whether this is a
release PR ('merge') or not ('squash'). If this is a hotfix merge, then I will
first merge the PR, and then merge that commit back into the dev branch.

The PR title is used as the merge commit message title, and any additional
copy beneath the `Please merge` message is used as the merge commit
message body (see example above).

**Feature branches will be deleted post-merge.**

    Please count approvals

Posts a comment on the PR containing the review approval count broken down by user teams.

    Please dismiss <review_id_goes_here> OR Please dismiss

Dismisses a review on a PR. This can be useful if a review cannot be dismissed
via the GitHub UI. This can occur if review comments are left on a commit which
has been removed due to a rebase and the reviewer is away e.g. on holiday.
If you use this command without an ID, you'll be provided a list of IDs to choose from.

Finally, here is a link to this PR's [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

Have a nice day.

**Comment by jowo-io** [comment]
Please count approvals

**Comment by jowo-io** [comment]
Thank you for checking approvals! Developer Approvals: 0, QA Approvals: 0, Total Approvals regardless of team: 0

**Review by culshaw — APPROVED** [review]

**Review by thealscott — APPROVED** [review]

**Review by melnichevv — APPROVED** [review]
LGTM

**Comment by jowo-io** [comment]
please count approvals

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Cannot read property '0' of undefined

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-undefined.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-undefined.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
per_page is not defined

**Comment by jowo-io** [comment]
octokit.users.listEmails is not a function

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not create review app

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
🤖 Beep beep boop. Here's your [review app](https://yunojuno-dev-228-pr-1.herokuapp.com).

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
Unknown error

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please deploy

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
appIdOrName is not defined

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
ReferenceError: pull_request is not defined

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Error: Expected response to be successful, got 422

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
User is already a collaborator on app platform-feature-yjp-39-diukzr.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please dismiss

**Comment by jowo-io** [comment]
please dismiss

**Comment by jowo-io** [comment]
No dismissible reviews found.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
No `***@yunojuno.com` email address was found for `pureth`.
New emails can be added to the hard-coded email map in the JunoBot code.

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please merge

**Comment by MihalisW** [comment]
**I'm sorry MihalisW, I'm afraid I can't do that.**

⚠️ Please check for merge conflicts

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚠️ Please check for merge conflicts

**Comment by jowo-io** [comment]
please help

**Comment by jowo-io** [comment]
JunoBot is here to help. Currently I support 4 commands:

    Please merge

This will trigger a merge request. In order to complete the merge, I will check
that the PR is mergeable (no conflicts), and that it has passed all of the status
checks. The merge strategy ('merge' or 'squash') is based on whether this is a
release PR ('merge') or not ('squash'). If this is a hotfix merge, then I will
first merge the PR, and then merge that commit back into the dev branch.

The PR title is used as the merge commit message title, and any additional
copy beneath the `Please merge` message is used as the merge commit
message body (see example above).

**Feature branches will be deleted post-merge.**

    Please count approvals

Posts a comment on the PR containing the review approval count broken down by user teams.

    Please dismiss <review_id_goes_here> OR Please dismiss

Dismisses a review on a PR. This can be useful if a review cannot be dismissed
via the GitHub UI. This can occur if review comments are left on a commit which
has been removed due to a rebase and the reviewer is away e.g. on holiday.
If you use this command without an ID, you'll be provided a list of IDs to choose from.

    Please operate

Give the commenter operate permissions on the PR's Heroku review app.

Have a nice day.

**Comment by jowo-io** [comment]
please count approvals

**Comment by jowo-io** [comment]
Thank you for checking approvals! Developer Approvals: 3, QA Approvals: 0, Total Approvals regardless of team: 3

**Comment by jowo-io** [comment]
please operate

**Comment by jowo-io** [comment]
Could not find the review app.

**Pull request closed without merging**
