### PR TITLE
YJP-0000: PR with clashing migrations

### PR DESCRIPTION
**Pull request by jowo-io**
test

### CODE REVIEW

**Review by melnichevv — APPROVED** [review]
LGTM

**Review by miphreal — APPROVED** [review]
PURRFECT :cat:

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict. Base branch (**dev**) is ahead. Please resolve.

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict (in core, work, profiles.
            Base branch (**dev**) is ahead.
            Please resolve.

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict (in core, work, profiles).
            Base branch (**dev**) is ahead.
            Please resolve.

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Pull request closed without merging**
