### PR TITLE
YJP-0000: Hotfix adding clashing migration

### PR DESCRIPTION
**Pull request by jowo-io**

### CODE REVIEW

**Comment by jowo-io** [comment]
Your pull request is now being monitored; comment "Please help" for more info. View the [review app](https://yunojuno-dev-228-pr-3.herokuapp.com).

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict (in profiles).
            Branch (**master**) is ahead.
            Please resolve.

**Comment by jowo-io** [comment]
please check

**Comment by jowo-io** [comment]
please check status

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict (in profiles).
            Branch (**master**) is ahead.
            Please resolve.

**Comment by jowo-io** [comment]
please help

**Comment by jowo-io** [comment]
JunoBot is here to help. Currently I support only 3 commands:

    Please merge

This will trigger a merge request. In order to complete the merge, I will check
that the PR is mergeable (no conflicts), and that it has passed all of the status
checks. The merge strategy ('merge' or 'squash') is based on whether this is a
release PR ('merge') or not ('squash'). If this is a hotfix merge, then I will
first merge the PR, and then merge that commit back into the dev branch.

The PR title is used as the merge commit message title, and any additional
copy beneath the `Please merge` message is used as the merge commit
message body (see example above).

**Feature branches will be deleted post-merge.**

    Please count approvals

Posts a comment on the PR containing the review approval count broken down by user teams.

    Please check status

Posts a comment on the PR containing a status update on the 'mergability' of the PR.

    Please dismiss <review_id_goes_here> OR Please dismiss

Dismisses a review on a PR. This can be useful if a review cannot be dismissed
via the GitHub UI. This can occur if review comments are left on a commit which
has been removed due to a rebase and the reviewer is away e.g. on holiday.
If you use this command without an ID, you'll be provided a list of IDs to choose from.

Finally, here is a link to this PR's [review app](https://yunojuno-dev-228-pr-3.herokuapp.com).

Have a nice day.

**Comment by jowo-io** [comment]
please tests

**Comment by jowo-io** [comment]
please test

**Comment by jowo-io** [comment]
hello world!

**Comment by jowo-io** [comment]
please check status

**Comment by jowo-io** [comment]
compareCommits is not defined

**Comment by jowo-io** [comment]
please check status

**Comment by jowo-io** [comment]
⚡️ Migrations will conflict (in profiles).
            Branch (**master**) is ahead.
            Please resolve.

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
Please check status

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Comment by MihalisW** [comment]
please help

**Pull request closed without merging**
